[package]
name = "komorebi"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.0", features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
    "macros",
] }
[build-dependencies]
sea-orm-cli = "1.1.10"
