[application]
port = 8000
hmac_secret = "w9zq6n+8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY=8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY"

[database]
host = "localhost"
port = 13306
username = "backend_user"
password = "backend_password"
database_name = "client"
max_connections = 100

redis_uri = "redis://127.0.0.1:6379"

[http]
timeout = 8
