[application]
port = 8000
hmac_secret = "w9zq6n+8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY=8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY8lO9Yy1FeIh3BV7y84pnE6uPNgqGVx9Jk4KY"

[database]
host = "localhost"
port = 5432
username = "backend_user"
password = "backend_user"
database_name = "newsletter"
schema = "zero2prod"

redis_uri = "redis://127.0.0.1:6379"
